package by.epam.atl.task2.controller;

public enum CommandName {
	CREATE_NOTEBOOK_COMMAND, 
	ADD_NOTE_TO_NOTEBOOK_COMMAND, 
	LOAD_NOTEBOOK_FROM_FILE_COMMAND,
	UNLOAD_NOTEBOOK_INTO_FILE_COMMAND,
	FIND_NOTES_BY_DATE, 
	FIND_NOTES_BY_CONTENT;
}
